services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - '1880:1880'
    volumes:
      - ./data/node-red:/data
    env_file:
      - .env
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:1880/']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - nodered-telegram-bot-network
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - node-red
    networks:
      - nodered-telegram-bot-network
    restart: always

networks:
  nodered-telegram-bot-network:
    driver: bridge
